import type { Metadata } from "next";
import { workSans } from "./font";
import "./globals.css";

export const metadata: Metadata = {
  title: "FAQ Design",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${workSans.className} antialiased`}>{children}</body>
    </html>
  );
}
